version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt

# 添加明确的构建命令
build:
  jobs:
    post_create:
      - pip install --upgrade pip
  commands:
    - sphinx-build -b html -d _build/doctrees docs _build/html

# 解决中文编码问题
formats:
  - htmlzip

# 设置中文环境变量
env:
  LC_ALL: "zh_CN.UTF-8"
  LANG: "zh_CN.UTF-8"
