version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  
sphinx:
  configuration: conf.py  # 指向根目录的 conf.py

python:
  install:
    - requirements: requirements.txt

# ==== 关键添加 ==== #
  # 显式设置构建命令
  build:
    commands:
      - sphinx-build -b html docs _build/html
