version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
sphinx:
  # 明确指向 conf.py（在项目根目录）
  configuration: conf.py  
  # 明确文档源目录为 docs/（与 conf.py 配合）
  source: docs/  
python:
  install:
    - requirements: requirements.txt
