version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
sphinx:
  configuration: conf.py
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
      # 添加镜像源配置
      pip:
        - --index-url=https://mirrors.aliyun.com/pypi/simple/
        - --trusted-host=mirrors.aliyun.com
