version: 2

build:
  os: ubuntu-18.04  # 构建环境的操作系统
  tools:
    python: "3.13"  # 构建使用的 Python 版本

sphinx:
  configuration: docs/conf.py  # 指向 Sphinx 的配置文件路径

python:
  install:
    - requirements: requirements.txt  # 安装依赖（如 Sphinx）
