version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"  # 构建使用的 Python 版本
sphinx:
  configuration: conf.py  # 指向 Sphinx 配置文件
python:
  install:
    - requirements: requirements.txt  # 安装文档构建所需依赖
