version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"  # 降低到稳定版本（Sphinx 对 3.10 支持更成熟）
sphinx:
  configuration: conf.py
  # 显式指定构建命令（避免默认命令的隐藏问题）
  build:
    command: sphinx-build -b html . $READTHEDOCS_OUTPUT/html
python:
  install:
    - requirements: requirements.txt
